import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getFirestore, collection, addDoc, setDoc, doc, onSnapshot, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
// Firebase configuration supplied for the H.D. Transformers project.
const firebaseConfig={apiKey:"AIzaSyDxdkJQjRJ1pmYxz233DXLLhbfigb4BMSU",authDomain:"hd-transformer.firebaseapp.com",projectId:"hd-transformer",storageBucket:"hd-transformer.firebasestorage.app",messagingSenderId:"641041626094",appId:"1:641041626094:web:6fca1898fcfd3972df54ff2",measurementId:"G-JV6XWX06S2"};
const app=initializeApp(firebaseConfig); const db=getFirestore(app);
import products from "./products.js";
const WHATSAPP_NUMBER="917949347417";
const DEFAULT_IMAGE="./assets/product-default.svg"; // change in one place if the owner gives another number
let state={products,shown:12,category:"",query:"",requestType:"inquiry",selected:null};

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const money=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);
const fallback=(el)=>{el.innerHTML='<div class="fallback">HD</div>'};
function categories(){return [...new Set(products.map(p=>p.category))].sort()}
function setupFilters(){const cats=categories(); $("#category").innerHTML='<option value="">All categories</option>'+cats.map(c=>`<option>${c}</option>`).join("");$("#categoryChips").innerHTML='<button class="chip active" data-cat="">All</button>'+cats.map(c=>`<button class="chip" data-cat="${c}">${c}</button>`).join("");$$(".chip").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;$("#category").value=state.category;$$(".chip").forEach(x=>x.classList.toggle("active",x===b));state.shown=12;render()});$("#category").onchange=e=>{state.category=e.target.value;$$(".chip").forEach(x=>x.classList.toggle("active",x.dataset.cat===state.category));state.shown=12;render()};$("#search").oninput=e=>{state.query=e.target.value.toLowerCase();state.shown=12;render()}}
function filtered(){return products.filter(p=>(!state.category||p.category===state.category)&&(!state.query||(`${p.name} ${p.category} ${JSON.stringify(p.specs)}`).toLowerCase().includes(state.query)))}
function card(p){const img=`<img src="${p.imageUrl||DEFAULT_IMAGE}" alt="${p.name}" onerror="this.src=DEFAULT_IMAGE">`;const specs=Object.entries(p.specs||{}).slice(0,4).map(([k,v])=>`<span class="spec">${k}: ${v}</span>`).join("");return `<article class="product"><div class="product-img">${img}</div><div class="product-body"><span class="product-cat">${p.category}</span><h3>${p.name}</h3><div class="price">${money(p.price)} <span class="muted">/ ${p.unit||"Piece"}</span></div><div class="specs">${specs}</div><div class="product-actions"><button data-view="${p.id}">Details</button><button class="buy" data-request="${p.id}">Enquire</button></div></div></article>`}
function render(){const list=filtered();$("#productGrid").innerHTML=list.slice(0,state.shown).map(card).join("")||`<div class="muted">No products matched your search.</div>`;$("#loadMore").style.display=state.shown<list.length?"flex":"none";$$("[data-request]").forEach(b=>b.onclick=()=>openRequest(products.find(p=>p.id===b.dataset.request),"inquiry"));$$("[data-view]").forEach(b=>b.onclick=()=>openRequest(products.find(p=>p.id===b.dataset.view),"inquiry","view"))}
function openRequest(p,type="inquiry",mode="normal"){state.selected=p||null;state.requestType=type;$("#modal").hidden=false;$("#fProduct").value=p?.name||"";$$(".request-tabs button").forEach(b=>b.classList.toggle("active",b.dataset.type===type));$("#modalTitle").textContent=type==="order"?"Order request":type==="callback"?"Request a callback":"Send enquiry";if(mode==="view"){const msg=`Please share details for ${p.name}.`;$("#requestForm textarea").value=msg}updateWA()}
function updateWA(){const f=$("#requestForm");const d=new FormData(f);const p=state.selected?.name||d.get("productName")||"General requirement";const msg=`Hello H.D. Transformers, I want to ${state.requestType}.\nProduct: ${p}\nName: ${d.get("name")||""}\nPhone: ${d.get("phone")||""}\nCity: ${d.get("city")||""}\nQuantity: ${d.get("quantity")||1}\nMessage: ${d.get("message")||""}`;$("#waRequest").href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(msg)}`;$("#waTop").href=`https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent("Hello H.D. Transformers, I want to discuss a transformer requirement.")}`}
function validate(){let ok=true;const f=$("#requestForm");$$("#requestForm input[required],#requestForm textarea[required]").forEach(x=>{const wrap=x.closest("label");const bad=!x.value.trim()||(x.name==="phone"&&!/^[0-9+()\\-\\s]{7,20}$/.test(x.value));wrap.classList.toggle("invalid",bad);if(bad){const e=wrap.querySelector(".err");if(e)e.textContent=x.name==="phone"?"Please enter a valid phone number.":"This field is required.";ok=false}});return ok}
async function submitRequest(e){e.preventDefault();$("#formStatus").textContent="";if(!validate()){ $("#formStatus").textContent="Please check the red fields."; return }const d=Object.fromEntries(new FormData(e.target).entries());const payload={...d,type:state.requestType,productId:state.selected?.id||null,productName:state.selected?.name||d.productName||"",productPrice:state.selected?.price||null,createdAt:serverTimestamp(),source:"website",status:"new",userAgent:navigator.userAgent};try{await addDoc(collection(db,state.requestType==="order"?"orders":state.requestType==="callback"?"callbacks":"inquiries"),payload);const customerKey=btoa(unescape(encodeURIComponent((d.phone||d.email||d.name).trim()))).replace(/[^a-zA-Z0-9]/g,"").slice(0,80);await setDoc(doc(db,"customers",customerKey),{name:d.name,phone:d.phone,email:d.email||"",city:d.city,lastProduct:payload.productName,lastRequestType:state.requestType,lastRequestAt:serverTimestamp()},{merge:true});$("#formStatus").style.color="#16824f";$("#formStatus").textContent="Request sent successfully. We will contact you shortly.";e.target.reset();$("#fProduct").value=state.selected?.name||"";updateWA();setTimeout(()=>{$("#modal").hidden=true;$("#formStatus").textContent=""},1400)}catch(err){console.error(err);$("#formStatus").style.color="#d63c3c";$("#formStatus").textContent="Could not send online. Please use WhatsApp or call the company."}}
$("#navToggle").onclick=()=>$("#mainNav").classList.toggle("open");$$("[data-close]").forEach(x=>x.onclick=()=>$("#modal").hidden=true);$$("[data-action]").forEach(x=>x.onclick=()=>openRequest(null,"inquiry"));$$(".request-tabs button").forEach(b=>b.onclick=()=>{state.requestType=b.dataset.type;$$(".request-tabs button").forEach(x=>x.classList.toggle("active",x===b));$("#modalTitle").textContent=state.requestType==="order"?"Order request":state.requestType==="callback"?"Request a callback":"Send enquiry";updateWA()});$("#requestForm").addEventListener("submit",submitRequest);$("#requestForm").addEventListener("input",updateWA);$("#loadMore").onclick=()=>{state.shown+=12;render()};setupFilters();render();updateWA();
onSnapshot(collection(db,"products"),snap=>{if(!snap.empty){state.products=snap.docs.map(d=>({id:d.id,...d.data()}));products.length=0;products.push(...state.products);setupFilters();render()}});
if("serviceWorker" in navigator){navigator.serviceWorker.register("./sw.js").catch(console.warn)}
