import { db, functions } from "./shared/firebase.js";
import { collection, query, where, onSnapshot, doc, onSnapshot as onDocSnapshot } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { httpsCallable } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-functions.js";
const DEFAULT_IMG="assets/default-transformer.svg";
const defaults={brandName:"H.D. Transformers",tagline:"Industrial Power Solutions",heroEyebrow:"Industrial Power Solutions • Jaipur, India",heroTitle:"Transformer engineering built for demanding power.",heroSubtitle:"Power, distribution, OLTC, dry-type and solar-duty transformers for industrial and renewable-energy applications.",aboutTitle:"Industrial capability, presented with clarity.",aboutText:"H.D. Transformers is a Jaipur-based transformer manufacturer with a growing industrial product portfolio.",aboutShort:"Industrial transformer manufacturing presence in Jaipur.",phone:"07949347417",whatsapp:"917949347417",email:"",address:"20-21-22, Vinayak Enclave, Near Bhagwati Nursery, Vishwakarma Industrial Area, Jaipur - 302013, Rajasthan, India.",accentColor:"#f0a51a",pattern:"grid",enquiriesOpen:true,orderRequestsOpen:true,rating:"4.4",reviewCount:"39"};
const state={products:[],categories:[],reviews:[],settings:{...defaults},filter:"all",search:"",featuredIndex:0};const submitInquiry=httpsCallable(functions,"submitInquiry");const $=id=>document.getElementById(id);const els={header:document.querySelector(".header"),nav:$("mainNav"),menu:$("menuBtn"),grid:$("productGrid"),filters:$("filters"),search:$("productSearch"),empty:$("emptyState"),dialog:$("requestDialog"),form:$("requestForm"),status:$("formStatus")};
function money(v){const n=Number(v);return Number.isFinite(n)?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n):""}function avail(v){return({available:"Available",made_to_order:"Made to order",limited:"Limited",unavailable:"Unavailable"})[v]||"Contact sales"}function scale(v){return Math.max(.7,Math.min(1.3,(Number(v)||100)/100))}function fallback(img){img.addEventListener("error",()=>{img.src=DEFAULT_IMG},{once:true})}
function applySettings(raw={}){const s=state.settings={...defaults,...raw};document.documentElement.style.setProperty("--accent",s.accentColor||"#f0a51a");document.documentElement.dataset.pattern=["grid","dots","none"].includes(s.pattern)?s.pattern:"grid";const txt={brandName:s.brandName,brandTagline:s.tagline,heroEyebrow:s.heroEyebrow,heroTitle:s.heroTitle,heroSubtitle:s.heroSubtitle,aboutTitle:s.aboutTitle,aboutText:s.aboutText,aboutShort:s.aboutShort,addressText:s.address,phoneText:s.phone,ratingValue:s.rating,reviewCount:`${s.reviewCount||state.reviews.length||0} reviews`};Object.entries(txt).forEach(([id,v])=>{const e=$(id);if(e&&v)e.textContent=v});$("heroAvailability").textContent=s.enquiriesOpen?"Open":"Paused";const tel=`tel:${String(s.phone).replace(/[^\d+]/g,"")}`,wa=`https://wa.me/${String(s.whatsapp).replace(/\D/g,"")}`;["phoneLink","footerPhone"].forEach(id=>{const e=$(id);if(e)e.href=tel});["whatsappLink","footerWA"].forEach(id=>{const e=$(id);if(e)e.href=wa});if($("emailLink")){$("emailLink").href=s.email?`mailto:${s.email}`:"#contact";$("emailText").textContent=s.email||"Ask for email"}}
function renderCategories(){const host=$("categoryGrid");if(!host)return;host.innerHTML="";state.categories.forEach(c=>{const a=document.createElement("a");a.className="category-card";a.href=`category.html?slug=${encodeURIComponent(c.slug)}`;const count=state.products.filter(p=>p.categorySlug===c.slug||p.category===c.name).length;a.innerHTML=`<small>${count} products</small><h3>${escapeHTML(c.name)}</h3><p>${escapeHTML(c.intro||"")}</p><span>View category →</span>`;host.appendChild(a)});if(!state.categories.length)host.innerHTML='<div class="loading">Categories are being prepared.</div>'}
function escapeHTML(v=""){return String(v).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]))}
function renderFilters(){els.filters.innerHTML="";const all=document.createElement("button");all.className=`filter ${state.filter==="all"?"active":""}`;all.dataset.filter="all";all.textContent="All";els.filters.appendChild(all);state.categories.slice(0,12).forEach(c=>{const b=document.createElement("button");b.className=`filter ${state.filter===c.name?"active":""}`;b.dataset.filter=c.name;b.textContent=c.name;els.filters.appendChild(b)})}
function filtered(){const q=state.search.trim().toLowerCase();return state.products.filter(p=>(state.filter==="all"||p.category===state.filter)&&(!q||`${p.name||""} ${p.category||""} ${p.description||""}`.toLowerCase().includes(q)))}
function openDetails(p){location.href=`product.html?slug=${encodeURIComponent(p.slug||p.id)}`}
function card(p){const art=document.createElement("article");art.className="product-card";const iw=document.createElement("button");iw.type="button";iw.className="product-image product-image-button";iw.onclick=()=>openDetails(p);const img=document.createElement("img");img.src=p.imageUrl||DEFAULT_IMG;img.alt=p.name||"Transformer";img.loading="lazy";img.style.objectFit=["cover","contain"].includes(p.imageFit)?p.imageFit:"contain";img.style.objectPosition=p.imagePosition||"center";img.style.transform=`scale(${scale(p.imageScale)})`;fallback(img);iw.appendChild(img);const tag=document.createElement("span");tag.className="tag";tag.textContent=p.category||"Transformer";const av=document.createElement("span");av.className=`avail ${p.availability||""}`;av.textContent=avail(p.availability);iw.append(tag,av);const body=document.createElement("div");body.className="product-body";const code=document.createElement("small");code.textContent=`HDT • ${(p.category||"PRODUCT").toUpperCase()}`;const h=document.createElement("button");h.className="product-title-button";h.textContent=p.name||"Unnamed product";h.onclick=()=>openDetails(p);const d=document.createElement("p");d.textContent=p.description||"Contact sales for complete specifications.";body.append(code,h,d);if(Array.isArray(p.specs)&&p.specs.length){const sp=document.createElement("div");sp.className="specs";p.specs.slice(0,4).forEach(s=>{if(!s?.label&&!s?.value)return;const x=document.createElement("div"),a=document.createElement("span"),b=document.createElement("strong");a.textContent=s.label||"Spec";b.textContent=s.value||"—";x.append(a,b);sp.appendChild(x)});body.appendChild(sp)}const bottom=document.createElement("div");bottom.className="product-bottom";const price=document.createElement("span");price.className="price";price.textContent=p.showPrice&&Number(p.price)>0?`${money(p.price)}${p.priceUnit?" / "+p.priceUnit:""}`:(p.priceLabel||"Get Latest Price");const acts=document.createElement("div");acts.className="actions";const details=document.createElement("button");details.className="mini details";details.textContent="Details";details.onclick=()=>openDetails(p);acts.appendChild(details);if(p.inquiryEnabled!==false){const iq=document.createElement("button");iq.className="mini enquiry";iq.textContent="Get Quote";iq.onclick=()=>openRequest(p,"inquiry");acts.appendChild(iq)}if(state.settings.orderRequestsOpen&&p.orderEnabled&&p.availability!=="unavailable"){const o=document.createElement("button");o.className="mini order";o.textContent="Order";o.onclick=()=>openRequest(p,"order");acts.appendChild(o)}bottom.append(price,acts);body.appendChild(bottom);art.append(iw,body);return art}
function renderProducts(){els.grid.innerHTML="";const list=filtered();list.forEach(p=>els.grid.appendChild(card(p)));els.empty.hidden=list.length!==0;renderFeatured();startFeaturedCarousel();renderCategories()}
function renderFeatured(){const list=state.products.filter(p=>p.active!==false);if(!list.length)return;const featured=list.filter(p=>p.featured);const pool=featured.length?featured:list;const p=pool[state.featuredIndex%pool.length];$("featuredName").textContent=p.name||"Featured Transformer";$("featuredCategory").textContent=p.category||"Transformer";$("featuredPrice").textContent=p.showPrice&&Number(p.price)>0?money(p.price):(p.priceLabel||"Get Latest Price");const img=$("featuredImage");img.src=p.imageUrl||DEFAULT_IMG;img.alt=p.name||"Featured transformer";img.style.objectFit=["cover","contain"].includes(p.imageFit)?p.imageFit:"contain";img.style.objectPosition=p.imagePosition||"center";img.style.transform=`scale(${scale(p.imageScale)})`;fallback(img)}
let featuredTimer=null;function startFeaturedCarousel(){if(featuredTimer)clearInterval(featuredTimer);featuredTimer=setInterval(()=>{if(state.products.length>1){state.featuredIndex=(state.featuredIndex+1)%Math.max(1,state.products.filter(p=>p.featured).length||state.products.length);renderFeatured()}},3500)}
function renderReviews(){const host=$("reviewGrid");if(!host)return;host.innerHTML="";state.reviews.slice(0,3).forEach(r=>{const a=document.createElement("article");a.className="review-card";a.innerHTML=`<div class="stars">${"★".repeat(Math.max(1,Math.min(5,Number(r.rating)||5)))}</div><p>${escapeHTML(r.text||`Feedback for ${r.productName||"H.D. Transformers"}`)}</p><strong>${escapeHTML(r.name||"Customer")}</strong><small>${escapeHTML(r.location||"")}${r.productName?" • "+escapeHTML(r.productName):""}</small>`;host.appendChild(a)});if(!state.reviews.length)host.innerHTML='<div class="review-card"><div class="stars">★★★★★</div><p>Customer feedback can be managed from the owner dashboard.</p><strong>H.D. Transformers</strong></div>'}
function setFieldError(id,on=true){const e=$(id);if(!e)return;e.classList.toggle("field-error",on);e.setAttribute("aria-invalid",on?"true":"false")}
function validateRequest(){
  const type=$("requestType").value.trim(), name=$("customerName").value.trim(), phone=$("customerPhone").value.trim(), email=$("customerEmail").value.trim(), qty=Number($("requestQuantity").value||0);
  document.querySelectorAll(".request-tab").forEach(b=>b.classList.toggle("tab-error",!type));
  setFieldError("customerName",name.length<2);setFieldError("customerPhone",phone.replace(/\D/g,"").length<6);setFieldError("customerEmail",!!email&&!/^\S+@\S+\.\S+$/.test(email));setFieldError("requestQuantity",qty<1||qty>999);
  if(!type){els.status.textContent="Please select Enquiry, Order Request or Request Callback.";els.status.className="form-status error";return false}
  if(name.length<2||phone.replace(/\D/g,"").length<6||qty<1||qty>999|| (!!email&&!/^\S+@\S+\.\S+$/.test(email))){els.status.textContent="Please correct the fields marked in red.";els.status.className="form-status error";return false}
  return true;
}
function openRequest(product=null,type=""){if(!state.settings.enquiriesOpen){alert("Online enquiries are currently paused. Please call the sales team.");return}if(type==="callback"&&product?.callbackEnabled===false)return;if(type==="inquiry"&&product?.inquiryEnabled===false)return;$("requestType").value=type;$("requestProductId").value=product?.id||"";$("requestProduct").value=product?.name||"";document.querySelectorAll(".request-tab").forEach(b=>{b.classList.toggle("active",b.dataset.type===type);b.classList.remove("tab-error")});$("submitRequest").textContent=type==="order"?"Send Order Request":type==="callback"?"Request Callback":"Send Enquiry";els.status.textContent=type?"":"Choose what you need first.";els.status.className=type?"form-status":"form-status hint";["customerName","customerPhone","customerEmail","requestQuantity"].forEach(id=>setFieldError(id,false));els.dialog.showModal()}
document.querySelectorAll(".request-tab").forEach(b=>b.onclick=()=>{const t=b.dataset.type;$("requestType").value=t;document.querySelectorAll(".request-tab").forEach(x=>{x.classList.toggle("active",x===b);x.classList.remove("tab-error")});$("submitRequest").textContent=t==="order"?"Send Order Request":t==="callback"?"Request Callback":"Send Enquiry";els.status.textContent="";els.status.className="form-status"});["headerEnquiry","heroEnquiry","floatingEnquiry"].forEach(id=>$(id).onclick=()=>openRequest());$("closeDialog").onclick=()=>els.dialog.close();
function formData(channel="dashboard"){return{type:$("requestType").value,channel,productId:$("requestProductId").value.trim(),productName:$("requestProduct").value.trim(),customerName:$("customerName").value.trim(),phone:$("customerPhone").value.trim(),email:$("customerEmail").value.trim(),city:$("customerCity").value.trim(),quantity:Math.max(1,Math.min(999,Number($("requestQuantity").value)||1)),message:$("requestMessage").value.trim()}}
$("sendWhatsAppRequest").onclick=async()=>{if(!validateRequest())return;const d=formData("whatsapp");try{await submitInquiry(d)}catch(e){console.warn("Lead logging failed before WhatsApp",e);els.status.textContent=e?.message?.includes("App Check")?"WhatsApp opened, but lead logging is blocked by Firebase App Check. Register the localhost debug token in Firebase Console.":"WhatsApp opened, but automatic lead logging failed. Please tell the owner to check Firebase.";els.status.className="form-status error"}const type=d.type==="order"?"Order Request":d.type==="callback"?"Callback Request":"Enquiry";const txt=["Hello H.D. Transformers,",`I want to send a ${type}.`,`Product: ${d.productName||"General requirement"}`,`Quantity: ${d.quantity}`,`Name: ${d.customerName}`,`Phone: ${d.phone}`,d.email?`Email: ${d.email}`:"",d.city?`City: ${d.city}`:"",d.message?`Message: ${d.message}`:""].filter(Boolean).join("\n");window.open(`https://wa.me/${String(state.settings.whatsapp||"").replace(/\D/g,"")}?text=${encodeURIComponent(txt)}`,"_blank","noopener,noreferrer")};
els.form.addEventListener("submit",async e=>{e.preventDefault();if(!validateRequest())return;const btn=$("submitRequest");btn.disabled=true;els.status.textContent="Sending securely…";els.status.className="form-status";try{const res=await submitInquiry(formData("dashboard"));els.status.textContent=`Sent successfully. Reference: ${res.data.reference}`;els.status.classList.add("success");els.form.reset();$("requestType").value="";document.querySelectorAll(".request-tab").forEach(x=>x.classList.remove("active"));setTimeout(()=>els.dialog.close(),1700)}catch(err){console.error(err);const appcheck=String(err?.message||err).toLowerCase().includes("app check");els.status.textContent=appcheck?"Could not send: Firebase App Check is blocking this local test. Register the browser debug token in Firebase Console, then reload.":(err?.message||"Could not send. Please check the highlighted fields and try again.");els.status.classList.add("error")}finally{btn.disabled=false}});
els.filters.onclick=e=>{const b=e.target.closest("[data-filter]");if(!b)return;state.filter=b.dataset.filter;renderFilters();renderProducts()};els.search.oninput=()=>{state.search=els.search.value;renderProducts()};els.menu.onclick=()=>{const open=els.nav.classList.toggle("open");document.body.classList.toggle("menu-open",open);els.menu.setAttribute("aria-expanded",String(open))};els.nav.onclick=e=>{if(e.target.matches("a")){els.nav.classList.remove("open");document.body.classList.remove("menu-open");els.menu.setAttribute("aria-expanded","false")}};const scrollHeader=()=>els.header.classList.toggle("scrolled",scrollY>20);scrollHeader();addEventListener("scroll",scrollHeader,{passive:true});$("year").textContent=new Date().getFullYear();
onDocSnapshot(doc(db,"site","public"),snap=>{applySettings(snap.exists()?snap.data():defaults);renderProducts()},()=>applySettings(defaults));onSnapshot(query(collection(db,"products"),where("active","==",true)),snap=>{state.products=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(Number(a.sortOrder)||9999)-(Number(b.sortOrder)||9999));renderFilters();renderProducts()},err=>{console.error(err);els.grid.innerHTML='<div class="loading">Catalogue is temporarily unavailable.</div>'});onSnapshot(query(collection(db,"categories"),where("active","==",true)),snap=>{state.categories=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(Number(a.sortOrder)||9999)-(Number(b.sortOrder)||9999));renderFilters();renderCategories()});onSnapshot(query(collection(db,"reviews"),where("active","==",true)),snap=>{state.reviews=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.date||"").localeCompare(String(a.date||"")));renderReviews()});
