export default [
  {
    "id": "p001",
    "name": "2000 KVA Three Phase Power Transformer",
    "category": "Power Transformer",
    "price": 2185000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "2000 KVA Three Phase Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Transformer Type": "Power Transformer",
      "Cooling Type": "Oil Cooled",
      "Mounting Type": "Floor Mounted",
      "Insulation Class": "A",
      "Phase": "Three Phase",
      "Transformer Power": "2000 KVA"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "2000-kva-three-phase-power-transformer"
  },
  {
    "id": "p002",
    "name": "Electrical Power Transformer",
    "category": "Power Transformer",
    "price": 1085000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Electrical Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Cooling Type": "Oil Cooled",
      "Usage/Application": "Electrical Power",
      "Mounting Type": "Ground Floor",
      "Transformer Type": "Power Transformer",
      "Phase": "3-Phase",
      "Power": "800 KVA",
      "Power Rating": "800 kVA"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "electrical-power-transformer"
  },
  {
    "id": "p003",
    "name": "3-Phase 1000 Kva Dry Type Transformer With OLTC",
    "category": "Power Transformer",
    "price": 1665000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "3-Phase 1000 Kva Dry Type Transformer With OLTC manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Material": "Stainless Steel",
      "Cooling Type": "Oil Cooled",
      "Warranty": "3 Year",
      "Usage": "Industrial",
      "Insulation Class": "H"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "3-phase-1000-kva-dry-type-transformer-with-oltc"
  },
  {
    "id": "p004",
    "name": "Industrial Electrical Power Transformer",
    "category": "Power Transformer",
    "price": 2500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Industrial Electrical Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Electrical Power Transformer",
      "Cooling Type": "Air Cooled",
      "Mounting Type": "Ground Floor",
      "Phase": "3-Phase",
      "Winding Material": "Copper"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "industrial-electrical-power-transformer"
  },
  {
    "id": "p005",
    "name": "Industrial Power Transformer",
    "category": "Power Transformer",
    "price": 865000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Industrial Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "500 kVA",
      "Type": "Electrical Power Transformer",
      "Cooling Type": "Oil Cooled",
      "Mounting Type": "Floor Mounted",
      "Winding Material": "Copper",
      "Phase": "Three Phase",
      "Insulation Class": "A"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "industrial-power-transformer"
  },
  {
    "id": "p006",
    "name": "5 Mva 3 Phase Oil Cooled Power Transformer",
    "category": "Power Transformer",
    "price": 4450000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "5 Mva 3 Phase Oil Cooled Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power Rating": "5000 kVA",
      "Type": "Oil Cooled Power Transformer",
      "Cooling Type": "Oil Cooled",
      "Brand": "H.D",
      "Insulation Class": "A"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "5-mva-3-phase-oil-cooled-power-transformer"
  },
  {
    "id": "p007",
    "name": "3 phase copper power transformer",
    "category": "Power Transformer",
    "price": 1490000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "3 phase copper power transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "1000 kVA",
      "Cooling Type": "Oil Cooled",
      "Material": "Mild Steel",
      "Insulation Class": "H",
      "AMC Available": "Yes",
      "Onsite Support Available": "Yes"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "3-phase-copper-power-transformer"
  },
  {
    "id": "p008",
    "name": "Three Phase Solar Inverter Duty Transformer",
    "category": "Power Transformer",
    "price": 1200000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Three Phase Solar Inverter Duty Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Winding Material": "Copper",
      "Cooling Type": "Oil Cooled",
      "Energy Efficiency Level": "Level 1",
      "Mounting Type": "Oil Type",
      "Insulation Class": "H",
      "Brand Name": "H. D. Transformer"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-solar-inverter-duty-transformer"
  },
  {
    "id": "p009",
    "name": "Step Up Transformer",
    "category": "Power Transformer",
    "price": 3500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Step Up Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "5000 kVA",
      "Type": "Inverter",
      "Cooling Type": "Oil Cooled",
      "Voltage Ratio": "2000kv",
      "Brand": "H.D"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "step-up-transformer"
  },
  {
    "id": "p010",
    "name": "Three Phase Distribution Transformer",
    "category": "Distribution Transformer",
    "price": 450000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Three Phase Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "400 kva",
      "Phase": "3 Phase",
      "Cooling Type": "Oil/Dry",
      "Type": "Distribution",
      "Voltage": "433 kV",
      "Transformer Brand": "HD",
      "Frequency": "50 Hz"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-distribution-transformer"
  },
  {
    "id": "p011",
    "name": "Power Distribution Transformer",
    "category": "Distribution Transformer",
    "price": 3850000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Power Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Transformer Type": "Isolation Transformer",
      "Power Rating": "5000 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Type": "Oil Cooled Power Transformer",
      "Insulation Class": "A",
      "Material": "Mild Steel",
      "Brand": "HD",
      "Frequency": "50 Hz"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "power-distribution-transformer"
  },
  {
    "id": "p012",
    "name": "Three Phase Power Distribution Transformer",
    "category": "Distribution Transformer",
    "price": 885000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": true,
    "imageUrl": "",
    "description": "Three Phase Power Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "500 kVA",
      "Material": "Mild Steel",
      "Cooling Type": "Oil Cooled",
      "Insulating Fluid": "Mineral Oil",
      "Winding Material": "Copper",
      "Frequency": "50Hz",
      "Efficiency": "95%",
      "Voltage": "440 V",
      "Ambient Temperature": "Up To 50 degree C"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-power-distribution-transformer"
  },
  {
    "id": "p013",
    "name": "Three Phase Electrical Power Transformer",
    "category": "Distribution Transformer",
    "price": 1190000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Electrical Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power Rating": "500 kVA",
      "Cooling Type": "Oil Cooled",
      "Material": "Mild Steel",
      "Phase": "3-Phase",
      "Power": "630 KVA",
      "Mounting Type": "Ground Mounted",
      "Transformer Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-electrical-power-transformer"
  },
  {
    "id": "p014",
    "name": "2Mva 3-Phase Oil Cooled Distribution Transformer",
    "category": "Distribution Transformer",
    "price": 2450000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "2Mva 3-Phase Oil Cooled Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Cooling Type": "ONAN",
      "Phase": "3 Phase",
      "Manufactured By": "H.D transformers",
      "Insulation Class": "A",
      "Power Rating": "1MVA",
      "Power": "500 kva",
      "Minimum Order Quantity": "1 Piece"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "2mva-3-phase-oil-cooled-distribution-transformer"
  },
  {
    "id": "p015",
    "name": "Oil-Cooled Distribution Transformer",
    "category": "Distribution Transformer",
    "price": 245000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Oil-Cooled Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power Rating": "160kVA",
      "Cooling Type": "Oil Cooled",
      "Mounting Type": "Ground Mounted",
      "Phase": "Three Phase",
      "Transformer Brand": "HD",
      "Winding Material": "Copper"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "oil-cooled-distribution-transformer"
  },
  {
    "id": "p016",
    "name": "Three Phase Distribution Transformers",
    "category": "Distribution Transformer",
    "price": 300000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Distribution Transformers manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "1500 kVA",
      "Material": "Aluminium",
      "Cooling Type": "Oil Cooled",
      "Phase": "3 Phase",
      "Energy Efficiency Level": "100",
      "Mounting Type": "H",
      "Insulation Class": "H",
      "AMC Available": "Yes",
      "Country of Origin": "Made in India"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-distribution-transformers"
  },
  {
    "id": "p017",
    "name": "1000 KVA Three Phase Distribution Transformer",
    "category": "Distribution Transformer",
    "price": 1385000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "1000 KVA Three Phase Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Voltage rating": "11 KVA",
      "Cooling Type": "Oil Cooled",
      "Winding Material": "Copper",
      "Insulating Fluid": "Mineral Oil",
      "Frequency": "50Hz",
      "Phase": "Three Phase",
      "Efficiency": "95%",
      "Voltage": "440 V",
      "Ambient Temperature": "Up To 50 degree C"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "1000-kva-three-phase-distribution-transformer"
  },
  {
    "id": "p018",
    "name": "Three Phase Oil Cooled Transformer",
    "category": "Three Phase Transformer",
    "price": 150000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Oil Cooled Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Brand": "HD",
      "Country of Origin": "Made in India"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-oil-cooled-transformer"
  },
  {
    "id": "p019",
    "name": "Oil Filled Transformer",
    "category": "Three Phase Transformer",
    "price": 890000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Oil Filled Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Oil Filled Transformer",
      "Cooling Type": "Oil Cooled",
      "Phase": "Three Phase",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "oil-filled-transformer"
  },
  {
    "id": "p020",
    "name": "3-Phase 250 Kva Distribution Transformer",
    "category": "Three Phase Transformer",
    "price": 345000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "3-Phase 250 Kva Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "250 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "3-phase-250-kva-distribution-transformer"
  },
  {
    "id": "p021",
    "name": "3 Phase 630 kva Distribution Transformers With OLTC",
    "category": "Three Phase Transformer",
    "price": 1425000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "3 Phase 630 kva Distribution Transformers With OLTC manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "630 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Tap Changer": "OLTC",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "3-phase-630-kva-distribution-transformers-with-oltc"
  },
  {
    "id": "p022",
    "name": "Three Phase Furnace Transformer",
    "category": "Three Phase Transformer",
    "price": 750000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Furnace Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Phase": "Three Phase",
      "Usage": "Industrial Furnace",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-furnace-transformer"
  },
  {
    "id": "p023",
    "name": "Three Phase Auxiliary Transformers",
    "category": "Three Phase Transformer",
    "price": 500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Auxiliary Transformers manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Phase": "Three Phase",
      "Usage": "Auxiliary",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-auxiliary-transformers"
  },
  {
    "id": "p024",
    "name": "500kVA 3-Phase Distribution Transformer",
    "category": "Three Phase Transformer",
    "price": 925000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "500kVA 3-Phase Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "500 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "500kva-3-phase-distribution-transformer"
  },
  {
    "id": "p025",
    "name": "Three Phase Unitized Substation",
    "category": "Three Phase Transformer",
    "price": 850000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Unitized Substation manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Phase": "Three Phase",
      "Type": "Unitized Substation",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-unitized-substation"
  },
  {
    "id": "p026",
    "name": "Copper Wound Transformer",
    "category": "Copper Wound Transformer",
    "price": 450000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Copper Wound Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Winding Material": "Copper",
      "Brand": "HD",
      "Phase": "Three Phase"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "copper-wound-transformer"
  },
  {
    "id": "p027",
    "name": "Three Phase Copper Wound Dry TypeTransformer",
    "category": "Copper Wound Transformer",
    "price": 500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Copper Wound Dry TypeTransformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "400 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Brand": "HD",
      "Winding Material": "Copper"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-copper-wound-dry-typetransformer"
  },
  {
    "id": "p028",
    "name": "100 Kva Dry Type Transformer",
    "category": "Copper Wound Transformer",
    "price": 150000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "100 Kva Dry Type Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Copper Wound Transformer",
      "Power": "500 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Winding Material": "Copper",
      "Transformer Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "100-kva-dry-type-transformer"
  },
  {
    "id": "p029",
    "name": "High Voltage Copper Wound Transformer",
    "category": "Copper Wound Transformer",
    "price": 3250000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "High Voltage Copper Wound Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Accuracy Class": "10",
      "Brand": "HD",
      "Material": "Copper",
      "Phase": "3 Phase",
      "Power": "440 V",
      "Frequency": "50 Hz"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "high-voltage-copper-wound-transformer"
  },
  {
    "id": "p030",
    "name": "3-Phase Oil Cooled OLTC Transformer",
    "category": "On Load Tap Changer",
    "price": 1065000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "3-Phase Oil Cooled OLTC Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Phase": "3 Phase",
      "Cooling Type": "Oil Cooled",
      "Tap Changer": "OLTC",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "3-phase-oil-cooled-oltc-transformer"
  },
  {
    "id": "p031",
    "name": "Cast Resin Dry Type Transformers",
    "category": "On Load Tap Changer",
    "price": 845000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Cast Resin Dry Type Transformers manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Cast Resin Dry Type",
      "Cooling Type": "Dry Type",
      "Phase": "Three Phase",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "cast-resin-dry-type-transformers"
  },
  {
    "id": "p032",
    "name": "2MVA 3-Phase Oltc Distribution Transformers",
    "category": "On Load Tap Changer",
    "price": 2390000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "2MVA 3-Phase Oltc Distribution Transformers manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "2 MVA",
      "Phase": "Three Phase",
      "Tap Changer": "OLTC",
      "Cooling Type": "Oil Cooled"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "2mva-3-phase-oltc-distribution-transformers"
  },
  {
    "id": "p033",
    "name": "Three Phase Solar Inverter Duty Transformer",
    "category": "Solar Inverter",
    "price": 1485000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Solar Inverter Duty Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Rated Power": "2 MVA",
      "Winding Material": "Copper",
      "Power": "630 kva",
      "Cooling Type": "ONAN",
      "Phase": "3 Phase",
      "Transformer Type": "3 Phase",
      "Dealing In": "Pan India",
      "Minimum Order Quantity": "1 Piece"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-solar-inverter-duty-transformer"
  },
  {
    "id": "p034",
    "name": "2 mva solar transformer",
    "category": "Solar Inverter",
    "price": 4650000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "2 mva solar transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Rated Power": "2 MVA",
      "Winding Material": "Copper",
      "Cooling Type": "ONAN",
      "Phase": "3 Phase",
      "Transformer Type": "3 Phase"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "2-mva-solar-transformer"
  },
  {
    "id": "p035",
    "name": "2000KVA OIL COOLED INVERTER DUTY SOLAR TRANSFORMER",
    "category": "Solar Inverter",
    "price": 2243000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "2000KVA OIL COOLED INVERTER DUTY SOLAR TRANSFORMER manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Country of Origin": "Made in India",
      "Dealing In": "Pan India",
      "Material": "Copper",
      "Type": "Distribution",
      "Cooling Type": "ONAN",
      "Minimum Order Quantity": "1 Piece"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "2000kva-oil-cooled-inverter-duty-solar-transformer"
  },
  {
    "id": "p036",
    "name": "OLTC Three Phase Distribution Transformer",
    "category": "OLTC Transformer",
    "price": 2985000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "OLTC Three Phase Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Material": "Copper",
      "Warranty": "3 Year",
      "Usage": "Industrial",
      "Country of Origin": "Made in India",
      "Transformer Type": "Distribution"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "oltc-three-phase-distribution-transformer"
  },
  {
    "id": "p037",
    "name": "500 kVA 3-Phase OLTC ON LOAD TAPE CHANGER Transformer",
    "category": "OLTC Transformer",
    "price": 1180000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "500 kVA 3-Phase OLTC ON LOAD TAPE CHANGER Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Material": "Copper",
      "Warranty": "3 year",
      "Usage": "Industrial",
      "Dealing In": "Pan india",
      "Minimum Order Quantity": "1 Piece"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "500-kva-3-phase-oltc-on-load-tape-changer-transformer"
  },
  {
    "id": "p038",
    "name": "1500 Kva 3-Phase Wind Transformer",
    "category": "Wind Transformer",
    "price": 1850000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "1500 Kva 3-Phase Wind Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "1500 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Usage": "Wind"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "1500-kva-3-phase-wind-transformer"
  },
  {
    "id": "p039",
    "name": "3 Phase 3000 kVA Oil Cooled Wind Transformer",
    "category": "Wind Transformer",
    "price": 2650000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "3 Phase 3000 kVA Oil Cooled Wind Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "3000 kVA",
      "Phase": "Three Phase",
      "Cooling Type": "Oil Cooled",
      "Usage": "Wind"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "3-phase-3000-kva-oil-cooled-wind-transformer"
  },
  {
    "id": "p040",
    "name": "Oil Filled Distribution Transformer",
    "category": "Oil Filled Transformer",
    "price": 900000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Oil Filled Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Oil Filled Distribution Transformer",
      "Cooling Type": "Oil Cooled",
      "Phase": "Three Phase",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "oil-filled-distribution-transformer"
  },
  {
    "id": "p041",
    "name": "Oil Filled Distribution Transformer",
    "category": "Oil Filled Transformer",
    "price": 900000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Oil Filled Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Oil Filled Distribution Transformer",
      "Cooling Type": "Oil Cooled",
      "Phase": "Three Phase",
      "Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "oil-filled-distribution-transformer"
  },
  {
    "id": "p042",
    "name": "1000 Kva Step Down Transformer",
    "category": "Step Down Transformer",
    "price": 1535000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "1000 Kva Step Down Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "500 kVA",
      "Type": "Isolation",
      "Winding Material": "Copper",
      "Warranty": "1 year",
      "Operational Life": "50",
      "Country of Origin": "Made in India"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "1000-kva-step-down-transformer"
  },
  {
    "id": "p043",
    "name": "500kva Step Down Transformer",
    "category": "Step Down Transformer",
    "price": 685000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "500kva Step Down Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "500 kVA",
      "Winding Material": "Copper",
      "Warranty": "5 year",
      "Country of Origin": "Made in India",
      "Usage": "Industrial"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "500kva-step-down-transformer"
  },
  {
    "id": "p044",
    "name": "800 KVA Dry Type Transformer",
    "category": "Dry Type Transformer",
    "price": 950000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "800 KVA Dry Type Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Transformer Type": "Dry Type Transformer",
      "Phase": "Three Phase",
      "Brand": "HD",
      "Country of Origin": "Made in India",
      "Winding Material": "Copper",
      "Transformer Power": "800 KVA"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "800-kva-dry-type-transformer"
  },
  {
    "id": "p045",
    "name": "On Load Tap Changer Transformer",
    "category": "Voltage Transformers",
    "price": 1200000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "On Load Tap Changer Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Phase": "3 Phase",
      "Frequency": "50 Hz",
      "Humidity": "95%",
      "Ambient Temperature": "50 Degree Celsius",
      "Impedance": "4.0%",
      "Transformer Power Rating": "500 KVA to 2500 KVA",
      "Material": "Stainless Steel",
      "Coil Material": "Copper"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "on-load-tap-changer-transformer"
  },
  {
    "id": "p046",
    "name": "500kVA 3-Phase Oil Cooled Distribution Transformer",
    "category": "Electrical Transformer",
    "price": 450000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "500kVA 3-Phase Oil Cooled Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power Rating": "100 kVA",
      "Cooling Type": "ONAN",
      "Type": "Distribution",
      "Country of Origin": "Made in India",
      "Phase": "Three Phase",
      "Usage": "Industrial"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "500kva-3-phase-oil-cooled-distribution-transformer"
  },
  {
    "id": "p047",
    "name": "200Kva 3-Phase Oil Cooled Distribution Transformer",
    "category": "Oil Cooled Distribution Transformer",
    "price": 330000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "200Kva 3-Phase Oil Cooled Distribution Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power Rating": "100 kVA",
      "Cooling Type": "ONAN",
      "Type": "Distribution",
      "Country of Origin": "Made in India",
      "Phase": "Three Phase",
      "Usage": "Industrial"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "200kva-3-phase-oil-cooled-distribution-transformer"
  },
  {
    "id": "p048",
    "name": "Three Phase Electrical Power Transformer",
    "category": "Electrical Power Transformer",
    "price": 1200000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Electrical Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power Rating": "500 kVA",
      "Cooling Type": "Oil Cooled",
      "Material": "Mild Steel",
      "Phase": "3-Phase",
      "Power": "630 KVA",
      "Mounting Type": "Ground Mounted",
      "Transformer Brand": "HD"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-electrical-power-transformer"
  },
  {
    "id": "p049",
    "name": "Cast Resin Transformer",
    "category": "Cast Resin Transformer",
    "price": 1165000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Cast Resin Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Cast Resin Transformer",
      "Cooling Type": "Air Cooled",
      "Mounting Type": "Ground Mounted",
      "Insulation Class": "H",
      "Phase": "3-Phase",
      "Power": "1000 kVA",
      "Country of Origin": "Made in India",
      "Frequency": "50 Hz",
      "Temperature Range": "80 Degree Celsius",
      "Winding Material": "Copper",
      "IP Rating": "IP21"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "cast-resin-transformer"
  },
  {
    "id": "p050",
    "name": "1000 KVA 50 Hz Three Phase Furnace Transformers",
    "category": "Furnace Transformers",
    "price": 965000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "1000 KVA 50 Hz Three Phase Furnace Transformers manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "1000 kVA",
      "Phase": "Three Phase",
      "Country of Origin": "Made in India",
      "Dealing In": "Pan India",
      "Material": "Copper",
      "Minimum Order Quantity": "1 Piece"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "1000-kva-50-hz-three-phase-furnace-transformers"
  },
  {
    "id": "p051",
    "name": "Auxiliary Current Transformers",
    "category": "Auxiliary Transformers",
    "price": 145000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Auxiliary Current Transformers manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Power": "100 kVA",
      "Winding Material": "Copper",
      "Cooling Type": "ONAN",
      "Phase": "3 Phase",
      "Country of Origin": "Made in India",
      "Usage": "Industrial"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "auxiliary-current-transformers"
  },
  {
    "id": "p052",
    "name": "High Voltage Power Transformer",
    "category": "Power Distribution Transformer",
    "price": 2500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "High Voltage Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "High Voltage Power Transformer",
      "Brand": "HD",
      "Country of Origin": "Made in India"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "high-voltage-power-transformer"
  },
  {
    "id": "p053",
    "name": "High Voltage Power Transformer",
    "category": "High Voltage Transformer",
    "price": 2500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "High Voltage Power Transformer manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "High Voltage Power Transformer",
      "Brand": "HD",
      "Country of Origin": "Made in India"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "high-voltage-power-transformer"
  },
  {
    "id": "p054",
    "name": "Three Phase Unitized Substation",
    "category": "Unitized Substation",
    "price": 2500000,
    "unit": "Piece",
    "currency": "INR",
    "available": true,
    "featured": false,
    "imageUrl": "",
    "description": "Three Phase Unitized Substation manufactured by H.D. Transformers, Jaipur. Specifications shown are based on the public product catalogue and should be confirmed with the company before purchase.",
    "specs": {
      "Type": "Unitized Substation",
      "Phase": "Three Phase",
      "Brand": "HD",
      "Country of Origin": "Made in India"
    },
    "sourceUrl": "https://www.hdtransformers.co.in/",
    "slug": "three-phase-unitized-substation"
  }
];
